using System;
using System.Collections.Generic;
using System.Text;

namespace ExportProductsToExcelFiles.AppModels
{
    public class ExcelProduct
    {
        public string GTIN { get; set; }
        public string SeasonCode { get; set; }
        public string Year { get; set; }
        public string StyleorPartNumber { get; set; }
        public string PartnerSKUUnique { get; set; }
        public string ParentSKU { get; set; }
        public string BrandName { get; set; }
        public string ProductTitle { get; set; }
        public string Department { get; set; }
        public string ProductType { get; set; }
        public string ProductSubtype { get; set; }
        public string SportType { get; set; }
        public string CountryofOrigin { get; set; }
        public string StyleorPartName { get; set; }
        public string ColourName { get; set; }
        public string ColourFamily { get; set; }
        public string Size { get; set; }
        public string SizingStandard { get; set; }
        public string TargetAgeRange { get; set; }
        public string SpecialSizeType { get; set; }
        public string Material { get; set; }
        public string LiningMaterial { get; set; }
        public string Neckline { get; set; }
        public string SleeveType { get; set; }
        public string Fit { get; set; }
        public string Occasion { get; set; }
        public string SkirtDressLength { get; set; }
        public string WaistType { get; set; }
        public string BraSupport { get; set; }
        public string CareInstructions { get; set; }
        public string AttributeKey1 { get; set; }
        public string AttributeValue1 { get; set; }
        public string AttributeKey2 { get; set; }
        public string AttributeValue2 { get; set; }
        public string AttributeKey3 { get; set; }
        public string AttributeValue3 { get; set; }
        public string AttributeKey4 { get; set; }
        public string AttributeValue4 { get; set; }
        public string AttributeKey5 { get; set; }
        public string AttributeValue5 { get; set; }
        public string LongDescription { get; set; }
        public string FeatureBullet1 { get; set; }
        public string FeatureBullet2 { get; set; }
        public string FeatureBullet3 { get; set; }
        public string FeatureBullet4 { get; set; }
        public string FeatureBullet5 { get; set; }
        public string ImageURL1 { get; set; }
        public string ImageURL2 { get; set; }
        public string ImageURL3 { get; set; }
        public string ImageURL4 { get; set; }
        public string ImageURL5 { get; set; }
        public string ImageURL6 { get; set; }
        public string ImageURL7 { get; set; }
        public string ShippingLengthcm { get; set; }
        public string ShippingHeightcm { get; set; }
        public string ShippingWidthDepthcm { get; set; }
        public string ShippingWeightKG { get; set; }
        public string ShippingDestination { get; set; }
        public string QuantityStock { get; set; }
        public string FulfilmentMethod { get; set; }
        public string ProcessingTime { get; set; }
        public string MSRPAE { get; set; }
        public string MSRPSA { get; set; }
        public string MSRPEG { get; set; }
        public string CostAED { get; set; }
        public string SellingPriceAED { get; set; }
        public string SellingPriceSAR { get; set; }
        public string SellingPriceEGP { get; set; }
        public string PromotionalPriceAED { get; set; }
        public string PromotionalPriceSAR { get; set; }
        public string PromotionalPriceEGP { get; set; }
        public string HSCode { get; set; }
        public string ModelNumber { get; set; }
        public string ModelName { get; set; }
        public string ProductLength { get; set; }
        public string LengthUnit { get; set; }
        public string ProductHeight { get; set; }
        public string HeightUnit { get; set; }
        public string ProductWidthDepth { get; set; }
        public string WidthDepthUnit { get; set; }
        public string ProductWeight { get; set; }
        public string WeightUnit { get; set; }
        public string Capacity { get; set; }
        public string CapacityUnit { get; set; }
        public string NumberofPieces { get; set; }
        public string SizeUnit { get; set; }
        public string ExteriorMaterial { get; set; }
        public string InteriorMaterial { get; set; }
        public string StrapMaterial { get; set; }
        public string CompatibleWith { get; set; }
        public string BaseMaterial { get; set; }
        public string SecondaryMaterial { get; set; }
        public string MaterialFinish { get; set; }
        public string TypesofShowerHead { get; set; }
        public string TypesofDispenser { get; set; }
        public string NumberofSpraySettings { get; set; }
        public string AssemblyRequired { get; set; }
        public string SetIncludes { get; set; }
        public string FillingMaterial { get; set; }
        public string ComfortLevel { get; set; }
        public string SheetType { get; set; }
        public string PackSize { get; set; }
        public string Formation { get; set; }
        public string TargetUseApplication { get; set; }
        public string TargetSkinType { get; set; }
        public string UVProtection { get; set; }
        public string BatterySize { get; set; }
        public string BatterySizeUnit { get; set; }
        public string BrandCompatibility { get; set; }
        public string ConnectionType { get; set; }
        public string CaseType { get; set; }
        public string ChargingType { get; set; }
        public string PhoneCaseMaterial { get; set; }
        public string AudioHeadphoneType { get; set; }
        public string WarrantyYears { get; set; }
        public string FrameColour { get; set; }
        public string FrameColourFamily { get; set; }
        public string LensColour { get; set; }
        public string LensColourFamily { get; set; }
        public string FrameShapeStyle { get; set; }
        public string LensFocalType { get; set; }
        public string LensMagnification { get; set; }
        public string LensType { get; set; }
        public string WidthProfile { get; set; }
        public string UpperMaterial { get; set; }
        public string SoleMaterial { get; set; }
        public string HeelType { get; set; }
        public string HeelProfile { get; set; }
        public string HeelHeight { get; set; }
        public string HeelHeightUnit { get; set; }
        public string BootShaftHeight { get; set; }
        public string BootShaftHeightUnit { get; set; }
        public string BootCircumference { get; set; }
        public string BootCircumferenceUnit { get; set; }
        public string ClosureFastener { get; set; }
        public string WardrobeDesign { get; set; }
        public string UpholsteryType { get; set; }
        public string SeatFilling { get; set; }
        public string SeatCushion { get; set; }
        public string WoodType { get; set; }
        public string WoodTone { get; set; }
        public string Shape { get; set; }
        public string NumberofDrawers { get; set; }
        public string NumberofDoors { get; set; }
        public string NumberofShelves { get; set; }
        public string NumberofSeats { get; set; }
        public string NumberofPanels { get; set; }
        public string Installation { get; set; }
        public string EnergyUsed { get; set; }
        public string AdditionalFeature1 { get; set; }
        public string AdditionalFeature2 { get; set; }
        public string AdditionalFeature3 { get; set; }
        public string Pattern { get; set; }
        public string MatsRugsCarpetDesign {get;set;}
        public string Technique { get; set; }
        public string StyleofCurtainLining { get; set; }
        public string DispenserType { get; set; }
        public string ScentsNotes { get; set; }
        public string AromatherapyType { get; set; }
        public string FineLuxuryMaterial { get; set; }
        public string BaseMaterialType { get; set; }
        public string StoneGem { get; set; }
        public string CaratWeight { get; set; }
        public string ClosureFastening { get; set; }
        public string ProductFeatures1 { get; set; }
        public string ProductFeatures2 { get; set; }
        public string ProductFeatures3 { get; set; }
        public string ProductFeatures4 { get; set; }
        public string ProductFeatures5 { get; set; }
        public string InkColourFamily { get; set; }
        public string PenMaterial { get; set; }
        public string PointorNibType { get; set; }
        public string PointSize { get; set; }
        public string PointSizeUnit { get; set; }
        public string Refillable { get; set; }
        public string WatchBandColour { get; set; }
        public string WatchBandColourFamily { get; set; }
        public string BandLength { get; set; }
        public string BandLengthUnit { get; set; }
        public string WatchBandMaterial { get; set; }
        public string WatchDialFaceType { get; set; }
        public string DialFaceDiameter { get; set; }
        public string DialFaceDiameterUnit { get; set; }
        public string WatchDialFaceColour { get; set; }
        public string WatchDialFaceColourFamily { get; set; }
        public string WatchMovement { get; set; }
        public string WatchCaseShape { get; set; }
        public string WatchBandClosure { get; set; }
        public string InterchangeableDialFace { get; set; }
        public string InterchangeableStrap { get; set; }

    }
}
